init:
  ps: |
        date
        $ErrorActionPreference = "Stop"

install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        date
        Bootstrap

build_script:
  ps: |
        cd fakepackage
        Exec { C:\MinGW\msys\1.0\bin\bash.exe $HOME\travis-tool.sh install_deps }
        Exec { C:\MinGW\msys\1.0\bin\bash.exe $HOME\travis-tool.sh run_tests }
