init:
  ps: |
        date
        $ErrorActionPreference = "Stop"

install:
  - ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        date
        Bootstrap
        date
        cp ..\travis-tool.sh .
        cd fakepackage
        echo '@echo off`nbash.exe ../travis-tool.sh "%*"' > .\travis-tool.sh.cmd
        cat .\travis-tool.sh.cmd
        echo '^travis-tool\.sh\.cmd$' >> .\.Rbuildignore
        cat .\.Rbuildignore

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests
