environment:
  WARNINGS_ARE_ERRORS: 1

init:
  ps: |
        date
        $ErrorActionPreference = "Stop"

install:
  - ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

deploy_script:
  - travis-tool.sh dump_logs ./push-artifact.sh

on_failure:
  - travis-tool.sh dump_logs
