init:
  ps: |
        date
        $ErrorActionPreference = "Stop"

install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        date
        Bootstrap
        date
        cp ..\travis-tool.sh .
        cd fakepackage

build_script:
  ps: |
        TravisTool install_deps

test_script:
  ps: |
        TravisTool run_tests
