init:
  ps: |
        date
        $ErrorActionPreference = "Stop"

install:
  - ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        date
        Bootstrap
        date
        cp ..\travis-tool.sh .
        cd fakepackage
        echo '@bash.exe ../travis-tool.sh "%*"' | Out-File -Encoding ASCII .\travis-tool.sh.cmd
        cat .\travis-tool.sh.cmd
        echo '^travis-tool\.sh\.cmd$' >> .\.Rbuildignore
        cat .\.Rbuildignore
  - cmd: type .\travis-tool.sh.cmd

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests
