init:
  ps: |
        date
        $ErrorActionPreference = "Stop"

install:
  - ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        date
        Bootstrap
        date
        cp ..\travis-tool.sh .
        cd fakepackage
        cp ..\travis-tool.sh.cmd .

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests
